### ISSUE TITLE
ошибка в admin/views/ad_main.php

### ISSUE THREAD

**Issue by deiloo** [Edrard/MSFC#1]
после установки нашел баг в админ панели:

admin/views/ad_main.php  676 строчька                       

```
                                       <input <?=($config['cron_multi']=='1')?'checked="yes"':'';?> type="checkbox" name="cron_auth" value="1" size="2" />
```

исправьте на name="cron_multi"

**Comment by Exinaus** [comment]
Спасибо.
Исправлено: [28.03.2013](https://github.com/Edrard/MSFC/commit/0844a45430b7e2e210e2ea3b8b91bade8b3227a3)
