### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by akeinhell** [Edrard/MSFC#10]
Parse error: syntax error, unexpected 'else' (T_ELSE) in /var/www/wot/public/MSFC/admin/views/ad_main.php on line 141

Приветствую коллега ) 
пытался разобратся куда вставить скобку, малость сломал глаз об код ) 
может совместными усилиями отрефакторим до красивости? )

**Comment by Exinaus** [comment]
Добрый день.

Кто то хочет помочь нам, самостоятельно, безвозмездно? Ура, ура. Давно такого не было.
Мы, в принципе, за любую движуху, кроме голодовки. Так что всегда будем рады помощи.
Напишите нам на [форуме](http://wot-news.com/forum/viewforum.php?f=30), что бы мы не только тут общались, если возможно. 

По поводу ошибки: там все в порядке с кодом, ошибки быть не должно. Открывающая скобка перед else должна быть в 101-й строке.

``` php
<?php if (!empty($adm_top_tanks)) { ?>
```

**Comment by akeinhell** [comment]
@Exinaus Отписался, жду конструктивного диалога
