### ISSUE TITLE
stronghold.php

### ISSUE THREAD

**Issue by Bealze** [Edrard/MSFC#11]
Undefined index: skirmish_battles_losses
Error on file /home/beals82/public_html/stat/stronghold.php, on line: 170

Code: <td><?php echo $lang['skirmish_'.$id]?></td>

**Comment by Exinaus** [comment]
Исправлено: [20.08.2015](https://github.com/Edrard/MSFC/commit/2c79efb6e13305fe2d75c807b7ef5b39accd8672)

**Comment by Bealze** [comment]
Исправлено: 20.08.2015

confimerd fix
