### ISSUE TITLE
not really a issue 

### ISSUE THREAD

**Issue by Bealze** [Edrard/MSFC#14]
where do i find documentations to add 

Доп функции:

went_players($roster,$start,$end); - ушедшие игроки за период
new_players($roster,$start,$end); - новые игроки за период

shown briefly here https://docs.google.com/document/d/1PWj81jEnCduP538RihEu3tImB18DaamBnyhxWC_bL7U/edit

**Comment by Edrard** [comment]
Sorry but there is no additional documentation :(
