### ISSUE TITLE
ad_main

### ISSUE THREAD

**Issue by BrandonBruceLee** [Edrard/MSFC#9]
![screenshot_1](https://cloud.githubusercontent.com/assets/3996904/3507688/888d50d6-0681-11e4-9b9b-7952a6570257.jpg)

**Comment by BrandonBruceLee** [comment]
и еще function / func_get.php
83 строка была:
    $api_lang = checklang($config['api_lang']);
после изменения на:
    $api_lang = checklang($config['lang']);
ошибка на главной пропала

**Comment by Exinaus** [comment]
Судя по всему вы сделали обновление файлов, но файл обновления БД у вас не сработал, или не запустился. Или вы обновили только часть файлов, не обновив те, которые запускают обновление БД.

Откройте файл ./update.php самостоятельно - он вам исправит Базу Данных.

**Comment by BrandonBruceLee** [comment]
установил полностью с нуля (все файлы удалил, база осталась та же)
![screenshot_1](https://cloud.githubusercontent.com/assets/3996904/3508424/122fdeb8-068b-11e4-890b-db8f67d8c63e.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/3996904/3508429/2a26c05e-068b-11e4-8b1e-8c8f932f5003.jpg)
ошибки те же

**Comment by Exinaus** [comment]
Проблема не в файлах, а в базе данных. Значения параметров (которые должны быть, но у вас почему то их нет, что и вызывает ошибку) - хранятся в базе данных. И только неверное обновление базы данных могло вызвать такую ошибку.
Обновление файлов в данном случае не несет никакого значения, ошибка из за старой базы данных.

Я не знаю почему и как вы не смогли обновить базу, слишком много вариантов, даже начинать гадать нет желания.
Я сейчас залил небольшое исправление на гитхаб, оно касается только файла update.php. Скачайте этот файл, потом в базе данных, в таблицах *_config (их может быть несколько, в зависимости от того сколько мультикланов), изменить параметр version на 300.0. И заново запустите update.php - он перепроверит структуру БД, и исправит ее если что.

Если не поможет, то есть простое решение как все исправить - переустановить базу данных, это можно сделать из админ панели. Минус такого решения - вы потеряете накопленные кроном данные. Хотя их можно забэкапить и вернуть потом в базу данных, вместе с содержимым.
Но если такое сделаете, то трюк с понижением версии модуля в базе, и запуском апдейтера еще раз все таки советую сделать, структура таблицы с данными о медалях изменилась. Апдейтер должен эту таблицу обновить.

**Comment by BrandonBruceLee** [comment]
Теперь все хорошо
